# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Dell.DisplayManager2.0
PackageVersion: 2.0.0.134
PackageLocale: en-US
Publisher: Dell Inc.
PackageName: Dell Display Manager 2.0
License: Proprietary
Copyright: (C)Dell Inc.
ShortDescription: Dell Display Manager 2.0
ManifestType: defaultLocale
ManifestVersion: 1.2.0

