# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Dell.DisplayManager
PackageVersion: 2.0
PackageLocale: en-US
Publisher: EnTech Taiwan
PublisherUrl: https://www.dell.com
PublisherSupportUrl: https://www.dell.com/support
PrivacyUrl: https://www.dell.com/privacy
PackageName: Dell Display Manager
PackageUrl: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=v9rk0&oscode=wt64a&productcode=dell-s2719dgf-monitor
License: Proprietary
LicenseUrl: https://www.dell.com/learn/us/en/uscorp1/terms-of-sale-consumer-license-agreements
ShortDescription: Dell Display Manager enhances everyday productivity through comprehensive management tools giving you optimal front of screen experience, efficient display management and easy, effortless multitasking.
ManifestType: defaultLocale
ManifestVersion: 1.2.0

